# Numpy

- Open source numerical library used for working with 
mathematical functions with multi-dimensional array and matrix data structures.

create numpy array

In [1]:
import numpy as np
mylist=[1,2,3]

np.array(mylist)


array([1, 2, 3])

In [4]:
nested_list=([1,2],[2,3],[3,4])
nested_list
np.array(nested_list)

array([[1, 2],
       [2, 3],
       [3, 4]])

In [9]:
np.arange(0,10,2) #0 -starting points
                  #10-ending points
                  #2-step size

array([0, 2, 4, 6, 8])

In [10]:
np.zeros((4,4)) #zeroes matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((4,4)) #once matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0,10,21) 

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [15]:
np.eye(5) #digonal matrix 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.random.rand(3) #gives 3 no. with uniform distribution bbtwn 0 and 1

array([0.46667921, 0.18819245, 0.54351744])

In [18]:
np.random.rand(3,3) #uniform distribition btwn 0 t0 1

array([[0.39759721, 0.92623558, 0.48847133],
       [0.91118503, 0.99134305, 0.47409162],
       [0.42953981, 0.32058375, 0.41785447]])

In [19]:
np.random.randn(3,3) #standard normal distribution mean 0 and sd 1

array([[-0.65503794, -0.63279478, -0.3963449 ],
       [ 1.40528608,  0.01661751,  0.3051596 ],
       [-0.36731864, -1.20280919, -0.68933088]])

In [23]:
np.random.randint(1,100,(2,2))

array([[20,  5],
       [59, 67]])

In [26]:
np.random.seed(10) #same random no generator
np.random.rand(4)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388])

In [27]:
arr=np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
arr.max()

24

In [31]:
arr.argmax() #higest index location

24

In [32]:
arr.argmin()#minimum index location

0

In [33]:
arr.dtype

dtype('int32')

numpy indexing

In [35]:
import numpy as np

arr=np.arange(0,11,1)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr[8]

8

In [37]:
arr[1:5]

array([1, 2, 3, 4])

In [38]:
 arr[0:5]=100

In [39]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [40]:
arr=np.arange(0,11)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
slice_of_arr=arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [45]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99])

In [46]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [47]:
arr_copy=arr.copy()

In [48]:
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [49]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [51]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [52]:
arr_2d.shape

(3, 3)

In [53]:
 arr_2d[1][1]

25

In [54]:
arr_2d[1,1]

25

In [56]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [58]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
bool_arr=arr >4

In [62]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

numpy operations

In [65]:
import numpy as np

arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [67]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [68]:
arr/arr

c:\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [69]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [71]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [73]:
np.log(arr)

c:\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [74]:
arr.mean()

4.5

In [75]:
arr.var()

8.25

In [76]:
arr.std()

2.8722813232690143

In [80]:
arr_2d=np.arange(0,25).reshape(5,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [82]:
arr_2d.sum()

300

In [83]:
arr_2d.sum(axis=0) #for rows axis=0

array([50, 55, 60, 65, 70])

In [84]:
arr_2d.sum(axis=1) #for columns axis =1

array([ 10,  35,  60,  85, 110])

In [86]:
import numpy as np

np.zeros(10)
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [88]:
np.arange(0,10)*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [89]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [90]:
# create an array of all the even integers from 10 to 50
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [93]:
# create a 3*3 matrix with values ranging from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
# use numpy to generate a random no between 0 and 1
np.random.rand(1)

array([0.49850701])

In [96]:
#use numpy to generate of 25 random no sampled from a standard normal distribution
np.random.randn(25)

array([ 0.26238882, -0.58273165,  1.36842193,  0.05336866,  1.49057364,
        0.75636693,  0.46964093, -0.23396259,  0.35365794,  1.78370094,
       -0.35030121, -0.9896496 , -0.63425417,  1.89876222,  1.99652279,
       -1.11867153,  2.18032831,  0.19046688,  1.2616859 ,  0.41765968,
        0.89395769,  0.04735517, -0.60842552, -0.26854813, -0.66630197])

In [98]:
np.arange(0,1,0.01).reshape(10,10)

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

In [99]:
#create an array of 20 linearly spaced points betwn 0 and 1
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])